### ISSUE TITLE
Criação da pagina sobre

### ISSUE THREAD

**Issue by dev-moraes** [raimundo-moraes/github-master#3]
Vocês poderiam criar uma pagina de sobre? Agradeço

**Comment by raimundo-moraes** [comment]
A pagina já está em produção

**Comment by dev-moraes** [comment]
Obrigado amigão estou aguardando
________________________________
De: Raimundo moraes ***@***.***>
Enviado: 24 de outubro de 2023 15:47
Para: raimundo-moraes/github-master ***@***.***>
Cc: moraes ***@***.***>; Author ***@***.***>
Assunto: Re: [raimundo-moraes/github-master] Criação da pagina sobre (Issue #3)


A pagina já está em produção
